name: movie_app
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  injectable: ^2.5.0
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  flutter_bloc: ^9.1.0
  dartz: ^0.10.1
  get_it: ^8.0.3
  path_provider: ^2.1.5
  dio: ^5.8.0+1
  connectivity_plus: ^5.0.2
  skeletonizer: ^1.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  injectable_generator: ^2.4.1



flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
